Adding "--auto_mixed_precision" option to enable AMP
This commit adds the `--auto_mixed_precision` option to the following scripts
 * `run_pretraining.py`
 * `run_squad.py`
 * `run_classifier.py`

Specifying the `--auto_mixed_precision` option enables AMP mode. This does two things
 1. Enable the AMP grappler optimization which will use fp16 (instead of fp32) for compute where possible
 2. Adding dynamic loss scaling to the optimizer.

In addition to the above change, this commit alss adds the `optimizer_type` option to the `run_squad.py` and `run_classifier.py` scripts ( `run_pretraining.py` already has it).

This commit also removes the `tf.compat.v1.disable_resource_variables()` statement from all the files that invoke training.

Using the loss_scale_optimizer (pullled in when AMP is enbaled) with the resource variables disabled leads the following error. Don't quite understand what is causing the error, but it seems that not disabling the resource variables gets rid of the error.

```
Traceback (most recent call last):
  File "run_pretraining.py", line 560, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "run_pretraining.py", line 533, in main
    estimator.train(input_fn=train_input_fn, max_steps=FLAGS.num_train_steps, hooks=hooks)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3089, in train
    rendezvous.raise_errors()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3084, in train
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1204, in _train_model_default
    self.config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2921, in _call_model_fn
    config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1163, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3179, in _model_fn
    features, labels, is_export_mode=is_export_mode)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1700, in call_without_tpu
    return self._call_model_fn(features, labels, is_export_mode=is_export_mode)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2031, in _call_model_fn
    estimator_spec = self._model_fn(features=features, **kwargs)
  File "run_pretraining.py", line 203, in model_fn
    total_loss, learning_rate, num_train_steps, num_warmup_steps, use_tpu, use_hvd, FLAGS.optimizer_type, use_amp)
  File "/root/bert/optimization.py", line 137, in create_optimizer
    train_op = optimizer.apply_gradients(zip(grads, tvars), global_step=global_step)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/experimental/loss_scale_optimizer.py", line 185, in apply_gradients
    self._distributed_apply, args=(grads_and_vars, global_step, name))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 2482, in merge_call
    return self._merge_call(merge_fn, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 2489, in _merge_call
    return merge_fn(self._strategy, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/autograph/impl/api.py", line 275, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/experimental/loss_scale_optimizer.py", line 220, in _distributed_apply
    control_flow_ops.no_op)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/smart_cond.py", line 59, in smart_cond
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1179, in cond
    return cond_v2.cond_v2(pred, true_fn, false_fn, name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/cond_v2.py", line 84, in cond_v2
    op_return_value=pred)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/experimental/loss_scale_optimizer.py", line 217, in apply_fn
    name + '-wrapped')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/experimental/loss_scale_optimizer.py", line 228, in _apply_gradients
    args=(grads_and_vars, global_step, name))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 2352, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 2711, in _call_for_each_replica
    return fn(*args, **kwargs)
  File "/root/bert/optimization.py", line 213, in apply_gradients
    [param.assign(next_param),
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variables.py", line 2052, in assign
    self._variable, value, use_locking=use_locking, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/state_ops.py", line 227, in assign
    validate_shape=validate_shape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 59, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/func_graph.py", line 595, in _create_op_internal
    compute_device)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3497, in _create_op_internal
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1940, in __init__
    (node_def.name, [i.dtype for i in inputs], input_types))
TypeError: In op 'Assign', input types ([tf.float32, tf.float32]) are not compatible with expected types ([tf.float32_ref, tf.float32])
```